name: Weekly update
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  auto-update:
    name: Automated benchmarks update
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"

      - run: yarn install --frozen-lockfile

      - name: Bump patch
        run: npm version patch --no-git-tag-version

      - name: Update
        id: update
        run: yarn run update-benchmarks

      - name: Build final result
        run: yarn build

      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public

      - name: Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automated weekly update of the benchmark.
          skip_dirty_check: true
          skip_fetch: true
